---
language: minimal

branches:
  only:
    - master

env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1 # Do not prompt for user input when using any SDK methods.

before_install:
  - openssl aes-256-cbc -K $encrypted_f911faa195a1_key -iv $encrypted_f911faa195a1_iv -in gcloud-service-account-secret.json.enc -out gcloud-service-account-secret.json -d

script:
  - curl https://sdk.cloud.google.com | bash > /dev/null
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file gcloud-service-account-secret.json
  - gcloud container clusters get-credentials gke-cluster --zone us-central1-a --project www-miketrout-dev
  - kubectl apply -f ambassador-rbac.yaml
  - kubectl apply -f ambassador-service.yaml
  - kubectl apply -f ambassador-mappings.yaml
  - kubectl apply -f api-miketrout-dev-certificate.yaml
  - kubectl apply -f api-miketrout-dev-ingress.yaml
