---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: experience-service-mapping
spec:
  prefix: /experience/
  rewrite: /experience/
  service: experience-service-service:60000
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: projects-service-mapping
spec:
  prefix: /projects/
  rewrite: /api/projects/
  service: projects-service-service:60001
---
apiVersion: getambassador.io/v1
kind: Mapping
metadata:
  name: skills-service-mapping
spec:
  prefix: /skills/
  service: skills-service-service:60002
