---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-miketrout-dev-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "api-miketrout-dev-static-ip"
    networking.gke.io/managed-certificates: "api-miketrout-dev-certificate"
spec:
  backend:
    serviceName: ambassador
    servicePort: 80
